// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatSessionsColumns holds the columns for the "chat_sessions" table.
	ChatSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "message_chat_session", Type: field.TypeUUID, Nullable: true},
	}
	// ChatSessionsTable holds the schema information for the "chat_sessions" table.
	ChatSessionsTable = &schema.Table{
		Name:       "chat_sessions",
		Columns:    ChatSessionsColumns,
		PrimaryKey: []*schema.Column{ChatSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chat_sessions_messages_chat_session",
				Columns:    []*schema.Column{ChatSessionsColumns[3]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "content", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"system", "user", "assistant"}},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "chat_session_user", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_chat_sessions_user",
				Columns:    []*schema.Column{UsersColumns[3]},
				RefColumns: []*schema.Column{ChatSessionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatSessionsTable,
		MessagesTable,
		UsersTable,
	}
)

func init() {
	ChatSessionsTable.ForeignKeys[0].RefTable = MessagesTable
	UsersTable.ForeignKeys[0].RefTable = ChatSessionsTable
}
