// Code generated by ent, DO NOT EDIT.

package message

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// EdgeChatSession holds the string denoting the chat_session edge name in mutations.
	EdgeChatSession = "chat_session"
	// Table holds the table name of the message in the database.
	Table = "messages"
	// ChatSessionTable is the table that holds the chat_session relation/edge.
	ChatSessionTable = "chat_sessions"
	// ChatSessionInverseTable is the table name for the ChatSession entity.
	// It exists in this package in order to avoid circular dependency with the "chatsession" package.
	ChatSessionInverseTable = "chat_sessions"
	// ChatSessionColumn is the table column denoting the chat_session relation/edge.
	ChatSessionColumn = "message_chat_session"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldContent,
	FieldRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleSystem, RoleUser, RoleAssistant:
		return nil
	default:
		return fmt.Errorf("message: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByChatSessionCount orders the results by chat_session count.
func ByChatSessionCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChatSessionStep(), opts...)
	}
}

// ByChatSession orders the results by chat_session terms.
func ByChatSession(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatSessionStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChatSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatSessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChatSessionTable, ChatSessionColumn),
	)
}
