execute_process(COMMAND uname -m OUTPUT_VARIABLE _arch OUTPUT_STRIP_TRAILING_WHITESPACE)
if("${_arch}" STREQUAL "amd64" OR "${_arch}" STREQUAL "x86_64")
    set(VCPKG_TARGET_ARCHITECTURE x64)
elseif("${_arch}" STREQUAL "arm64" OR "${_arch}" STREQUAL "aarch64")
    set(VCPKG_TARGET_ARCHITECTURE arm64)
else()
    message(FATAL_ERROR "Unsupported Linux architecture: ${_arch}")
endif()
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_LIBRARY_LINKAGE dynamic)
