"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from defdap.utils import report_progress

class Map(ABC):
    """
    Base class for a map. Contains common functionality for all maps.

    Attributes
    ----------

    _grains : list of defdap.base.Grain
        List of grains.
    sel_grain : defdap.base.grain
        The last selected grain

    """
    def __init__(self, file_name, data_type=..., experiment=..., increment=..., frame=..., map_name=...) -> None:
        """

        Parameters
        ----------
        file_name : str
            Path to EBSD file, including name, excluding extension.
        data_type : str, {'OxfordBinary', 'OxfordText'}
            Format of EBSD data file.

        """
        ...
    
    @abstractmethod
    def load_data(self, file_name, data_type=...): # -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, key):
        ...
    
    @property
    def grains(self): # -> None:
        ...
    
    @property
    def x_dim(self): # -> Literal[0]:
        ...
    
    @property
    def y_dim(self): # -> Literal[0]:
        ...
    
    def crop(self, map_data, **kwargs):
        ...
    
    def mask(self, map_data, **kwargs):
        ...
    
    def set_homog_point(self, **kwargs): # -> MapPlot:
        ...
    
    def plot_grain_numbers(self, dilate_boundaries=..., ax=..., **kwargs): # -> MapPlot:
        """Plot a map with grains numbered.

        Parameters
        ----------
        dilate_boundaries : bool, optional
            Set to true to dilate boundaries.
        ax : matplotlib.axes.Axes, optional
            axis to plot on, if not provided the current active axis is used.
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.plotting.MapPlot.add_grain_numbers`

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    def locate_grain(self, click_event=..., display_grain=..., **kwargs):
        """Interactive plot for identifying grains.

        Parameters
        ----------
        click_event : optional
            Click handler to use.
        display_grain : bool, optional
            If true, plot slip traces for grain selected by click.
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.base.Map.plot_default`

        """
        ...
    
    def click_grain_id(self, event, plot, display_grain): # -> None:
        """Event handler to capture clicking on a map.

        Parameters
        ----------
        event :
            Click event.
        plot : defdap.plotting.MapPlot
            Plot to capture clicks from.
        display_grain : bool
            If true, plot the selected grain alone in pop-out window.

        """
        ...
    
    def draw_line_profile(self, **kwargs):
        """Interactive plot for drawing a line profile of data.

        Parameters
        ----------
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.base.Map.plot_default`

        """
        ...
    
    def calc_line_profile(self, plot, start_end, **kwargs): # -> None:
        """Calculate and plot the line profile.

        Parameters
        ----------
        plot : defdap.plotting.MapPlot
            Plot to calculate the line profile for.
        start_end : array_like
            Selected points (x0, y0, x1, y1).
        kwargs : dict, optional
            Keyword arguments passed to :func:`matplotlib.pyplot.plot`

        """
        ...
    
    @report_progress("constructing neighbour network")
    def build_neighbour_network(self): # -> Generator[float, Any, None]:
        """Construct a list of neighbours

        """
        ...
    
    def display_neighbours(self, **kwargs):
        ...
    
    def click_grain_neighbours(self, event, plot): # -> None:
        """Event handler to capture clicking and show neighbours of selected grain.

        Parameters
        ----------
        event :
            Click event.
        plot : defdap.plotting.MapPlot
            Plot to monitor.

        """
        ...
    
    @property
    def proxigram(self): # -> None:
        """Proxigram for a map.

        Returns
        -------
        numpy.ndarray
            Distance from a grain boundary at each point in map.

        """
        ...
    
    @report_progress("calculating proxigram")
    def calc_proxigram(self, num_trials=...): # -> Generator[float, Any, Any]:
        """Calculate distance from a grain boundary at each point in map.

        Parameters
        ----------
        num_trials : int, optional
            number of trials.

        """
        ...
    
    def plot_map(self, map_name, component=..., **kwargs): # -> MapPlot:
        """Plot a map of the data.

        Parameters
        ----------
        map_name : str
            Map data name to plot i.e. e, max_shear, euler_angle, orientation.
        component : int or tuple of int or str
            Component of the map data to plot. This is either the tensor
            component (int or tuple of ints) or the name of a calculation
            to be applied e.g. 'norm', 'all_euler' or 'IPF_x'.
        kwargs
            All arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot
            Plot containing map.

        """
        ...
    
    def calc_grain_average(self, map_data, grain_ids=...): # -> NDArray[float64]:
        """Calculate grain average of any DIC map data.

        Parameters
        ----------
        map_data : numpy.ndarray
            Array of map data to grain average. This must be cropped!
        grain_ids : list, optional
            grain_ids to perform operation on, set to -1 for all grains.

        Returns
        -------
        numpy.ndarray
            Array containing the grain average values.

        """
        ...
    
    def grain_data_to_map(self, name): # -> NDArray[float64]:
        ...
    
    def grain_data_to_map_data(self, grain_data, grain_ids=..., bg=...): # -> NDArray[Any]:
        """Create a map array with each grain filled with the given
        values.

        Parameters
        ----------
        grain_data : list or numpy.ndarray
            Grain values. This can be a single value per grain or RGB
            values.
        grain_ids : list of int or int, optional
            IDs of grains to plot for. Use -1 for all grains in the map.
        bg : int or real, optional
            Value to fill the background with.

        Returns
        -------
        grain_map: numpy.ndarray
            Array filled with grain data values

        """
        ...
    
    def plot_grain_data_map(self, map_data=..., grain_data=..., grain_ids=..., bg=..., **kwargs): # -> MapPlot:
        """Plot a grain map with grains coloured by given data. The data
        can be provided as a list of values per grain or as a map which
        a grain average will be applied.

        Parameters
        ----------
        map_data : numpy.ndarray, optional
            Array of map data. This must be cropped! Either mapData or 
            grain_data must be supplied.
        grain_data : list or np.array, optional
            Grain values. This an be a single value per grain or RGB
            values. You must supply either mapData or grain_data.
        grain_ids: list of int or int, optional
            IDs of grains to plot for. Use -1 for all grains in the map.
        bg: int or real, optional
            Value to fill the background with.
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.plotting.MapPlot.create`

        Returns
        -------
        plot: defdap.plotting.MapPlot
            Plot object created

        """
        ...
    
    def plot_grain_data_ipf(self, direction, map_data=..., grain_data=..., grain_ids=..., **kwargs): # -> PolePlot:
        """
        Plot IPF of grain reference (average) orientations with
        points coloured by grain average values from map data.

        Parameters
        ----------
        direction : numpy.ndarray
            Vector of reference direction for the IPF.
        map_data : numpy.ndarray
            Array of map data. This must be cropped! Either mapData or
            grain_data must be supplied.
        grain_data : list or np.array, optional
            Grain values. This an be a single value per grain or RGB
            values. You must supply either mapData or grain_data.
        grain_ids: list of int or int, optional
            IDs of grains to plot for. Use -1 for all grains in the map.
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.quat.Quat.plot_ipf`

        """
        ...
    


class Grain(ABC):
    """
    Base class for a grain.

    Attributes
    ----------
    grain_id : int

    owner_map : defdap.base.Map

    """
    def __init__(self, grain_id, owner_map, group_id) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def extreme_coords(self): # -> tuple[Any, ...]:
        """Coordinates of the bounding box for a grain.

        Returns
        -------
        int, int, int, int
            minimum x, minimum y, maximum x, maximum y.

        """
        ...
    
    def centre_coords(self, centre_type=..., grain_coords=...): # -> tuple[int, int]:
        """
        Calculates the centre of the grain, either as the centre of the
        bounding box or the grains centre of mass.

        Parameters
        ----------
        centre_type : str, optional, {'box', 'com'}
            Set how to calculate the centre. Either 'box' for centre of
            bounding box or 'com' for centre of mass. Default is 'box'.
        grain_coords : bool, optional
            If set True the centre is returned in the grain coordinates
            otherwise in the map coordinates. Defaults is grain.

        Returns
        -------
        int, int
            Coordinates of centre of grain.

        """
        ...
    
    def grain_outline(self, bg=..., fg=...): # -> NDArray[Any]:
        """Generate an array of the grain outline.

        Parameters
        ----------
        bg : int
            Value for points not within grain.
        fg : int
            Value for points within grain.

        Returns
        -------
        numpy.ndarray
            Bounding box for grain with :obj:`~numpy.nan` outside the grain and given number within.

        """
        ...
    
    def plot_outline(self, ax=..., plot_scale_bar=..., **kwargs): # -> GrainPlot:
        """Plot the outline of the grain.

        Parameters
        ----------
        ax : matplotlib.axes.Axes
            axis to plot on, if not provided the current active axis is used.
        plot_scale_bar : bool
            plots the scale bar on the grain if true.
        kwargs : dict
            keyword arguments passed to :func:`defdap.plotting.GrainPlot.add_map`

        Returns
        -------
        defdap.plotting.GrainPlot

        """
        ...
    
    def grain_data(self, map_data):
        """Extract this grains data from the given map data.

        Parameters
        ----------
        map_data : numpy.ndarray
            Array of map data. This must be cropped!

        Returns
        -------
        numpy.ndarray
            Array containing this grains values from the given map data.

        """
        ...
    
    def grain_map_data(self, map_data=..., grain_data=..., bg=...): # -> NDArray[Any]:
        """Extract a single grain map from the given map data.

        Parameters
        ----------
        map_data : numpy.ndarray
            Array of map data. This must be cropped! Either this or
            'grain_data' must be supplied and 'grain_data' takes precedence.
        grain_data : numpy.ndarray
            Array of data at each point in the grain. Either this or
            'mapData' must be supplied and 'grain_data' takes precedence.
        bg : various, optional
            Value to fill the background with. Must be same dtype as
            input array.

        Returns
        -------
        numpy.ndarray
            Grain map extracted from given data.

        """
        ...
    
    def grain_map_data_coarse(self, map_data=..., grain_data=..., kernel_size=..., bg=...): # -> NDArray[Any]:
        """
        Create a coarsened data map of this grain only from the given map
        data. Data is coarsened using a kernel at each pixel in the
        grain using only data in this grain.

        Parameters
        ----------
        map_data : numpy.ndarray
            Array of map data. This must be cropped! Either this or
            'grain_data' must be supplied and 'grain_data' takes precedence.
        grain_data : numpy.ndarray
            List of data at each point in the grain. Either this or
            'mapData' must be supplied and 'grain_data' takes precedence.
        kernel_size : int, optional
            Size of kernel as the number of pixels to dilate by i.e 1
            gives a 3x3 kernel.
        bg : various, optional
            Value to fill the background with. Must be same dtype as
            input array.

        Returns
        -------
        numpy.ndarray
            Map of this grains coarsened data.

        """
        ...
    
    def plot_grain_data(self, map_data=..., grain_data=..., **kwargs): # -> GrainPlot:
        """
        Plot a map of this grain from the given map data.

        Parameters
        ----------
        map_data : numpy.ndarray
            Array of map data. This must be cropped! Either this or
            'grain_data' must be supplied and 'grain_data' takes precedence.
        grain_data : numpy.ndarray
            List of data at each point in the grain. Either this or
            'mapData' must be supplied and 'grain_data' takes precedence.
        kwargs : dict, optional
            Keyword arguments passed to :func:`defdap.plotting.GrainPlot.create`

        """
        ...
    
    def plot_map(self, map_name, component=..., **kwargs): # -> GrainPlot:
        """Plot a map of the data.

        Parameters
        ----------
        map_name : str
            Map data name to plot i.e. e, max_shear, euler_angle, orientation.
        component : int or tuple of int or str
            Component of the map data to plot. This is either the tensor
            component (int or tuple of ints) or the name of a calculation
            to be applied e.g. 'norm', 'all_euler' or 'IPF_x'.
        kwargs
            All arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot
            Plot containing map.

        """
        ...
    


