"""
This type stub file was generated by pyright.
"""

from defdap.crystal_utils import *

class Phase:
    def __init__(self, name, laue_group, space_group, lattice_params) -> None:
        """
        Parameters
        ----------
        name : str
            Name of the phase
        laue_group : int
            Laue group
        space_group : int
            Space group
        lattice_params : tuple
            Lattice parameters in order (a,b,c,alpha,beta,gamma)

        """
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def c_over_a(self): # -> None:
        ...
    
    def print_slip_systems(self): # -> None:
        """Print a list of slip planes (with colours) and slip directions.

        """
        ...
    


class CrystalStructure:
    def __init__(self, name, symmetries, vertices, faces) -> None:
        ...
    


over_root2 = ...
sqrt3over2 = ...
c_over_a = ...
crystalStructures = ...
class SlipSystem:
    """Class used for defining and performing operations on a slip system.

    """
    def __init__(self, slip_plane, slip_dir, crystal_structure, c_over_a=...) -> None:
        """Initialise a slip system object.

        Parameters
        ----------
        slip_plane: numpy.ndarray
            Slip plane.
        slip_dir: numpy.ndarray
            Slip direction.
        crystal_structure : defdap.crystal.CrystalStructure
            Crystal structure of the slip system.
        c_over_a : float, optional
            C over a ratio for hexagonal crystals.

        """
        ...
    
    def __eq__(self, right) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def slip_plane_label(self): # -> str:
        """Return the slip plane label. For example '(111)'.

        Returns
        -------
        str
            Slip plane label.

        """
        ...
    
    @property
    def slip_dir_label(self): # -> str:
        """Returns the slip direction label. For example '[110]'.

        Returns
        -------
        str
            Slip direction label.

        """
        ...
    
    def generate_family(self): # -> set[Any]:
        """Generate the family of slip systems which this system belongs to.

        Returns
        -------
        list of SlipSystem
            The family of slip systems.

        """
        ...
    
    @staticmethod
    def load(name, crystal_structure, c_over_a=..., group_by=...): # -> tuple[list[list[Any]], list[str]]:
        """
        Load in slip systems from file. 3 integers for slip plane
        normal and 3 for slip direction. Returns a list of list of slip
        systems grouped by slip plane.

        Parameters
        ----------
        name : str
            Name of the slip system file (without file extension)
            stored in the defdap install dir or path to a file.
        crystal_structure : defdap.crystal.CrystalStructure
            Crystal structure of the slip systems.
        c_over_a : float, optional
            C over a ratio for hexagonal crystals.
        group_by : str, optional
            How to group the slip systems, either by slip plane ('plane')
            or slip system family ('family') or don't group (None).

        Returns
        -------
        list of list of SlipSystem
            A list of list of slip systems grouped slip plane.

        Raises
        ------
        IOError
            Raised if not 6/8 integers per line.

        """
        ...
    
    @staticmethod
    def group(slip_systems, group_by): # -> list[list[Any]]:
        """
        Groups slip systems by their slip plane.

        Parameters
        ----------
        slip_systems : list of SlipSystem
            A list of slip systems.
        group_by : str
            How to group the slip systems, either by slip plane ('plane')
            or slip system family ('family').

        Returns
        -------
        list of list of SlipSystem
            A list of list of grouped slip systems.

        """
        ...
    
    @staticmethod
    def print_slip_system_directory(): # -> None:
        """
        Prints the location where slip system definition files are stored.

        """
        ...
    


