"""
This type stub file was generated by pyright.
"""

__all__ = ['create_l_matrix', 'create_q_matrix', 'convert_idc', 'equavlent_indicies', 'project_to_orth', 'pos_idc', 'reduce_idc', 'safe_int_cast', 'idc_to_string', 'str_idx']
def create_l_matrix(a, b, c, alpha, beta, gamma, convention=...): # -> NDArray[float64]:
    """ Construct L matrix based on Page 22 of
    Randle and Engle - Introduction to texture analysis"""
    ...

def create_q_matrix(l_matrix): # -> NDArray[Any]:
    """ Construct matrix of reciprocal lattice vectors to transform
    plane normals See C. T. Young and J. L. Lytton, J. Appl. Phys.,
    vol. 43, no. 4, pp. 1408–1417, 1972."""
    ...

def check_len(val, length): # -> None:
    ...

def convert_idc(in_type, *, dir=..., plane=...): # -> tuple[Any, ...]:
    """
    Convert between Miller and Miller-Bravais indices.

    Parameters
    ----------
    in_type : str {'m', 'mb'}
        Type of indices provided. If 'm' converts from Miller to
        Miller-Bravais, opposite for 'mb'.
    dir : tuple of int or equivalent, optional
        Direction to convert. This OR `plane` must me provided.
    plane : tuple of int or equivalent, optional
        Plane to convert. This OR `direction` must me provided.

    Returns
    -------
    tuple of int
        The converted plane or direction.

    """
    ...

def equavlent_indicies(crystal_symm, symmetries, *, dir=..., plane=..., c_over_a=..., in_type=...): # -> list[Any]:
    ...

def project_to_orth(c_over_a, *, dir=..., plane=..., in_type=...): # -> Any:
    """
    Project from crystal aligned coordinates to an orthogonal set.

    Parameters
    ----------
    in_type : str {'m', 'mb'}
        Type of indices provided
    dir : tuple of int or equivalent, optional
        Direction to convert. This OR `plane` must me provided.
    plane : tuple of int or equivalent, optional
        Plane to convert. This OR `direction` must me provided.

    Returns
    -------


    """
    ...

def pos_idc(vec): # -> tuple[Any, ...] | None:
    """
    Return a consistent positive version of a set of indices.

    Parameters
    ----------
    vec : tuple of int or equivalent
        Indices to convert.

    Returns
    -------
    tuple of int
        Positive version of indices.

    """
    ...

def reduce_idc(vec): # -> tuple[Any, ...]:
    """
    Reduce indices to lowest integers

    Parameters
    ----------
    vec : tuple of int or equivalent
        Indices to reduce.

    Returns
    -------
    tuple of int
        The reduced indices.

    """
    ...

def safe_int_cast(vec, tol=...): # -> tuple[Any, ...]:
    """
    Cast a tuple of floats to integers, raising an error if rounding is
    over a tolerance.

    Parameters
    ----------
    vec : tuple of float or equivalent
        Vector to cast.
    tol : float
        Tolerance above which an error is raised.

    Returns
    -------
    tuple of int

    Raises
    ------
    ValueError
        If the rounding is over the tolerance for any value.

    """
    ...

def idc_to_string(idc, brackets=..., str_type=...): # -> str:
    """
    String representation of a set of indicies.

    Parameters
    ----------
    idc : collection of int
    brackets : str
        String of opening and closing brackets eg '()'
    str_type : str {'unicode', 'tex'}

    Returns
    -------
    str

    """
    ...

def str_idx(idx, str_type=...): # -> str:
    """
    String representation of an index with overbars.

    Parameters
    ----------
    idx : int
    str_type : str {'unicode', 'tex'}

    Returns
    -------
    str

    """
    ...

