"""
This type stub file was generated by pyright.
"""

from defdap.utils import report_progress
from defdap import base

class Map(base.Map):
    """
    Class to encapsulate an EBSD map and useful analysis and plotting
    methods.

    Attributes
    ----------
    step_size : float
        Step size in micron.
    phases : list of defdap.crystal.Phase
        List of phases.
    mis_ori : numpy.ndarray
        Map of misorientation.
    mis_ori_axis : list of numpy.ndarray
        Map of misorientation axis components.
    origin : tuple(int)
        Map origin (x, y). Used by linker class where origin is a
        homologue point of the maps.

    data : defdap.utils.Datastore
        Must contain after loading data (maps):
            phase : numpy.ndarray
                1-based, 0 is non-indexed points
            euler_angle : numpy.ndarray
                stored as (3, y_dim, x_dim) in radians
        Generated data:
            orientation : numpy.ndarray of defdap.quat.Quat
                Quaterion for each point of map. Shape (y_dim, x_dim).
            grain_boundaries : BoundarySet
            phase_boundaries : BoundarySet
            grains : numpy.ndarray of int
                Map of grains. Grain numbers start at 1 here but everywhere else
                grainID starts at 0. Regions that are smaller than the minimum
                grain size are given value -2. Remnant boundary points are -1.
            KAM : numpy.ndarray
                Kernal average misorientaion map.
            GND : numpy.ndarray
                GND scalar map.
            Nye_tensor : numpy.ndarray
                3x3 Nye tensor at each point.
        Derived data:
            grain_data_to_map : numpy.ndarray
                Grain list data to map data from all grains

    """
    MAPNAME = ...
    def __init__(self, *args, **kwargs) -> None:
        """
        Initialise class and load EBSD data.

        Parameters
        ----------
        *args, **kwarg
            Passed to base constructor

        """
        ...
    
    @report_progress("loading EBSD data")
    def load_data(self, file_name, data_type=...): # -> Generator[str, Any, None]:
        """Load in EBSD data from file.

        Parameters
        ----------
        file_name : pathlib.Path
            Path to EBSD file
        data_type : str, {'OxfordBinary', 'OxfordText', 'EdaxAng', 'PythonDict'}
            Format of EBSD data file.

        """
        ...
    
    def save(self, file_name, data_type=..., file_dir=...): # -> None:
        """Save EBSD map to file.

        Parameters
        ----------
        file_name : str
            Name of file to save to, it must not already exist.
        data_type : str, {'OxfordText'}
            Format of EBSD data file to save.
        file_dir : str
            Directory to save the file to.

        """
        ...
    
    @property
    def crystal_sym(self):
        """Crystal symmetry of the primary phase.

        Returns
        -------
        str
            Crystal symmetry

        """
        ...
    
    @property
    def c_over_a(self):
        """C over A ratio of the primary phase

        Returns
        -------
        float or None
            C over A ratio if hexagonal crystal structure otherwise None

        """
        ...
    
    @property
    def num_phases(self): # -> int | None:
        ...
    
    @property
    def primary_phase(self):
        """Primary phase of the EBSD map.

        Returns
        -------
        defdap.crystal.Phase
            Primary phase

        """
        ...
    
    @property
    def scale(self): # -> None:
        ...
    
    @report_progress("rotating EBSD data")
    def rotate_data(self): # -> Generator[float, Any, None]:
        """Rotate map by 180 degrees and transform quats accordingly.

        """
        ...
    
    def calc_euler_colour(self, map_data, phases=..., bg_colour=...): # -> NDArray[Any]:
        ...
    
    def calc_ipf_colour(self, map_data, direction, phases=..., bg_colour=...): # -> NDArray[Any]:
        ...
    
    def plot_euler_map(self, phases=..., bg_colour=..., **kwargs): # -> MapPlot:
        """Plot an orientation map in Euler colouring

        Parameters
        ----------
        phases : list of int
            Which phases to plot for
        kwargs
            All arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    def plot_ipf_map(self, direction, phases=..., bg_colour=..., **kwargs): # -> MapPlot:
        """
        Plot a map with points coloured in IPF colouring,
        with respect to a given sample direction.

        Parameters
        ----------
        direction : np.array len 3
            Sample direction.
        phases : list of int
            Which phases to plot IPF data for.
        bg_colour : np.array len 3
            Colour of background (i.e. for phases not plotted).
        kwargs
            Other arguments passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    def plot_phase_map(self, **kwargs): # -> MapPlot:
        """Plot a phase map.

        Parameters
        ----------
        kwargs
            All arguments passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    @report_progress("calculating KAM")
    def calc_kam(self): # -> Generator[float, Any, NDArray[signedinteger[Any]]]:
        """
        Calculates Kernel Average Misorientaion (KAM) for the EBSD map,
        based on a 3x3 kernel. Crystal symmetric equivalences are not
        considered. Stores result as `KAM`.

        """
        ...
    
    @report_progress("calculating Nye tensor")
    def calc_nye(self): # -> Generator[float, Any, tuple[Any, NDArray[float64]]]:
        """
        Calculates Nye tensor and related GND density for the EBSD map.
        Stores result as `Nye_tensor` and `GND`. Uses the crystal
        symmetry of the primary phase.

        """
        ...
    
    @report_progress("building quaternion array")
    def calc_quat_array(self): # -> Generator[float, Any, ndarray[Any, Any]]:
        """Build quaternion array

        """
        ...
    
    def filter_data(self, misori_tol=...): # -> ndarray[Any, dtype[float64]]:
        ...
    
    @report_progress("finding grain boundaries")
    def find_boundaries(self, misori_tol=...): # -> Generator[float, Any, tuple[BoundarySet, BoundarySet]]:
        """Find grain and phase boundaries

        Parameters
        ----------
        misori_tol : float
            Critical misorientation in degrees.

        """
        ...
    
    @report_progress("constructing neighbour network")
    def build_neighbour_network(self): # -> Generator[float, Any, None]:
        ...
    
    def plot_phase_boundary_map(self, dilate=..., **kwargs): # -> MapPlot:
        """Plot phase boundary map.

        Parameters
        ----------
        dilate : bool
            If true, dilate boundary.
        kwargs
            All other arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    def plot_boundary_map(self, **kwargs): # -> MapPlot:
        """Plot grain boundary map.

        Parameters
        ----------
        kwargs
            All arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    @report_progress("finding grains")
    def find_grains(self, min_grain_size=...): # -> Generator[Any, Any, NDArray[Any]]:
        """Find grains and assign IDs.

        Parameters
        ----------
        min_grain_size : int
            Minimum grain area in pixels.

        """
        ...
    
    def plot_grain_map(self, **kwargs): # -> MapPlot:
        """Plot a map with grains coloured.

        Parameters
        ----------
        kwargs
            All arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    @report_progress("calculating grain mean orientations")
    def calc_grain_av_oris(self): # -> Generator[float, Any, None]:
        """Calculate the average orientation of grains.

        """
        ...
    
    @report_progress("calculating grain misorientations")
    def calc_grain_mis_ori(self, calc_axis=...): # -> Generator[float, Any, None]:
        """Calculate the misorientation within grains.

        Parameters
        ----------
        calc_axis : bool
            Calculate the misorientation axis if True.

        """
        ...
    
    def plot_mis_ori_map(self, component=..., **kwargs): # -> MapPlot:
        """Plot misorientation map.

        Parameters
        ----------
        component : int, {0, 1, 2, 3}
            0 gives misorientation, 1, 2, 3 gives rotation about x, y, z
        kwargs
            All other arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    
    @report_progress("calculating grain average Schmid factors")
    def calc_average_grain_schmid_factors(self, load_vector, slip_systems=...): # -> Generator[float, Any, None]:
        """
        Calculates Schmid factors for all slip systems, for all grains,
        based on average grain orientation.

        Parameters
        ----------
        load_vector :
            Loading vector, e.g. [1, 0, 0].
        slip_systems : list, optional
            Slip planes to calculate Schmid factor for, maximum of all
            planes calculated if not given.

        """
        ...
    
    @report_progress("calculating RDR values")
    def calc_rdr(self): # -> Generator[float, Any, None]:
        """Calculates Relative Displacent Ratio values for all grains"""
        ...
    
    def plot_average_grain_schmid_factors_map(self, planes=..., directions=..., **kwargs): # -> MapPlot:
        """
        Plot maximum Schmid factor map, based on average grain
        orientation (for all slip systems unless specified).

        Parameters
        ----------
        planes : list, optional
            Plane ID(s) to consider. All planes considered if not given.
        directions : list, optional
            Direction ID(s) to consider. All directions considered if not given.
        kwargs
            All other arguments are passed to :func:`defdap.plotting.MapPlot.create`.

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    


class Grain(base.Grain):
    """
    Class to encapsulate a grain in an EBSD map and useful analysis and
    plotting methods.

    Attributes
    ----------
    ebsd_map : defdap.ebsd.Map
        EBSD map this grain is a member of.
    owner_map : defdap.ebsd.Map
        EBSD map this grain is a member of.
    phase_id : int

    phase : defdap.crystal.Phase

    data : defdap.utils.Datastore
        Must contain after creating:
            point : list of tuples
                (x, y)
        Generated data:
            GROD : numpy.ndarray
                Grain reference orientation distribution magnitude
            GROD_axis : numpy.ndarray
                Grain reference orientation distribution direction
        Derived data:
            Map data to list data from the map the grain is part of


    mis_ori_list : list
        MisOri at each point in grain.
    mis_ori_axis_list : list
        MisOri axes at each point in grain.
    ref_ori : defdap.quat.Quat
        Average ori of grain
    average_mis_ori
        Average mis_ori of grain.
    average_schmid_factors : list
        List of list Schmid factors (grouped by slip plane).
    slip_trace_angles : list
        Slip trace angles in screen plane.
    slip_trace_inclinations : list
         Angle between slip plane and screen plane.

    """
    def __init__(self, grain_id, ebsdMap, group_id) -> None:
        ...
    
    @property
    def crystal_sym(self):
        """Temporary"""
        ...
    
    def calc_average_ori(self): # -> None:
        """Calculate the average orientation of a grain.

        """
        ...
    
    def build_mis_ori_list(self, calc_axis=...): # -> None:
        """Calculate the misorientation within given grain.

        Parameters
        ----------
        calc_axis : bool
            Calculate the misorientation axis if True.

        """
        ...
    
    def calc_grod(self): # -> tuple[NDArray[signedinteger[Any]], Any]:
        ...
    
    def calc_ipf_colour(self, grain_data, direction, bg_colour=...): # -> ndarray[Any, Any]:
        ...
    
    def calc_euler_colour(self, grain_data, bg_colour=...):
        ...
    
    def plot_ref_ori(self, direction=..., **kwargs): # -> PolePlot:
        """Plot the average grain orientation on an IPF.

        Parameters
        ----------
        direction : numpy.ndarray
            Sample direction for IPF.
        kwargs
            All other arguments are passed to :func:`defdap.quat.Quat.plot_ipf`.

        Returns
        -------
        defdap.plotting.PolePlot

        """
        ...
    
    def plot_ori_spread(self, direction=..., **kwargs): # -> PolePlot:
        """Plot all orientations within a given grain, on an IPF.

        Parameters
        ----------
        direction : numpy.ndarray
            Sample direction for IPF.
        kwargs
            All other arguments are passed to :func:`defdap.quat.Quat.plot_ipf`.

        Returns
        -------
        defdap.plotting.PolePlot

        """
        ...
    
    def plot_unit_cell(self, fig=..., ax=..., plot=..., **kwargs): # -> CrystalPlot:
        """Plot an unit cell of the average grain orientation.

        Parameters
        ----------
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on
        ax : matplotlib.figure.Figure
            Matplotlib figure to plot on
        plot : defdap.plotting.PolePlot
            defdap plot to plot the figure to.
        kwargs
            All other arguments are passed to :func:`defdap.quat.Quat.plot_unit_cell`.

        """
        ...
    
    def plot_mis_ori(self, component=..., **kwargs): # -> GrainPlot:
        """Plot misorientation map for a given grain.

        Parameters
        ----------
        component : int, {0, 1, 2, 3}
            0 gives misorientation, 1, 2, 3 gives rotation about x, y, z.
        kwargs
            All other arguments are passed to :func:`defdap.ebsd.plot_grain_data`.

        Returns
        -------
        defdap.plotting.GrainPlot

        """
        ...
    
    def calc_average_schmid_factors(self, load_vector, slip_systems=...): # -> None:
        """Calculate Schmid factors for grain, using average orientation.

        Parameters
        ----------
        load_vector : numpy.ndarray
            Loading vector, i.e. [1, 0, 0]
        slip_systems : list, optional
            Slip planes to calculate Schmid factor for. Maximum for all planes
            used if not set.

        """
        ...
    
    def calc_rdr(self): # -> None:
        """Calculate Relative Displacement Ratio values."""
        ...
    
    @property
    def slip_traces(self): # -> list[Any] | None:
        """Returns list of slip trace angles.

        Returns
        -------
        list
            Slip trace angles based on grain orientation in calc_slip_traces.

        """
        ...
    
    def print_slip_traces(self): # -> None:
        """Print a list of slip planes (with colours) and slip directions

        """
        ...
    
    def calc_slip_traces(self, slip_systems=...): # -> None:
        """Calculates list of slip trace angles based on grain orientation.

        Parameters
        -------
        slip_systems : defdap.crystal.SlipSystem, optional

        """
        ...
    


class BoundarySet:
    def __init__(self, ebsd_map, points_x, points_y) -> None:
        ...
    
    @classmethod
    def from_image(cls, ebsd_map, image_x, image_y): # -> Self:
        ...
    
    @classmethod
    def from_boundary_segments(cls, b_segs): # -> Self:
        ...
    
    @property
    def points(self): # -> set[Any]:
        ...
    
    @property
    def image_x(self): # -> NDArray[Any]:
        ...
    
    @property
    def image_y(self): # -> NDArray[Any]:
        ...
    
    @property
    def image(self): # -> NDArray[Any]:
        ...
    
    @property
    def lines(self):
        ...
    
    @staticmethod
    def boundary_points_to_lines(*, boundary_points_x=..., boundary_points_y=...): # -> tuple[Any, ...]:
        ...
    


class BoundarySegment:
    def __init__(self, ebsdMap, grain1, grain2) -> None:
        ...
    
    def __eq__(self, right) -> bool:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def addBoundaryPoint(self, point, kind, owner_grain): # -> None:
        ...
    
    def boundary_point_pairs(self, kind): # -> list[Any]:
        """Return pairs of points either side of the boundary. The first
        point is always in grain1
        """
        ...
    
    @property
    def boundary_point_pairs_x(self): # -> list[Any]:
        """Return pairs of points either side of the boundary. The first
        point is always in grain1
        """
        ...
    
    @property
    def boundary_point_pairs_y(self): # -> list[Any]:
        """Return pairs of points either side of the boundary. The first
        point is always in grain1
        """
        ...
    
    @property
    def boundary_lines(self):
        """Return line points along this boundary segment"""
        ...
    
    def misorientation(self): # -> tuple[Any, Any]:
        ...
    


class Linker:
    """Class for linking multiple EBSD maps of the same region for analysis of deformation.

    Attributes
    ----------
    ebsd_maps : list(ebsd.Map)
        List of `ebsd.Map` objects that are linked.
    links : list(tuple(int))
        List of grain link. Each link is stored as a tuple of
        grain IDs (one from each map stored in same order of maps).
    plots : list(plotting.MapPlot)
        List of last opened plot of each map.

    """
    def __init__(self, ebsd_maps) -> None:
        """Initialise linker and set ebsd maps

        Parameters
        ----------
        ebsd_maps : list(ebsd.Map)
            List of `ebsd.Map` objects that are linked.

        """
        ...
    
    def set_origin(self, **kwargs): # -> None:
        """Interactive tool to set origin of each EBSD map.

        Parameters
        ----------
        kwargs
            Keyword arguments passed to :func:`defdap.ebsd.Map.plot_default`

        """
        ...
    
    def click_set_origin(self, event, plot): # -> None:
        """Event handler for clicking to set origin of map.

        Parameters
        ----------
        event
            Click event.
        plot : defdap.plotting.MapPlot
            Plot to capture clicks from.

        """
        ...
    
    def start_linking(self): # -> None:
        """Start interactive grain linking process of each EBSD map.

        """
        ...
    
    def click_grain_guess(self, event, plot): # -> None:
        """Guesses grain position in other maps, given click on one.

        Parameters
        ----------
        event
            Click handler.
        plot : defdap.plotting.Plot
            Plot to capture clicks from.

        """
        ...
    
    def make_link(self, event, plot): # -> None:
        """Make a link between the EBSD maps after clicking.

        """
        ...
    
    def reset_links(self): # -> None:
        """Reset links.

        """
        ...
    
    def set_ref_ori_from_master(self): # -> None:
        """Loop over each map (not first/reference) and each link.
        Sets refOri of linked grains to refOri of grain in first map.

        """
        ...
    
    def update_misori(self, calc_axis=...): # -> None:
        """Recalculate misorientation for linked grain (not for first map)

        Parameters
        ----------
        calc_axis : bool
            Calculate the misorientation axis if True.

        """
        ...
    


