"""
This type stub file was generated by pyright.
"""

import numpy as np
import pathlib
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Optional, TextIO, Type
from defdap.crystal import Phase

class EBSDDataLoader(ABC):
    """Class containing methods for loading and checking EBSD data

    """
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def get_loader(data_type: str, file_name: pathlib.Path) -> Type[EBSDDataLoader]:
        ...
    
    def check_metadata(self) -> None:
        """
        Checks that the number of phases from metadata matches
        the amount of phases loaded.

        """
        ...
    
    def check_data(self) -> None:
        ...
    
    @abstractmethod
    def load(self, file_name: pathlib.Path) -> None:
        ...
    


class OxfordTextLoader(EBSDDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Read an Oxford Instruments .ctf file, which is a HKL single
        orientation file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    


class EdaxAngLoader(EBSDDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Read an EDAX .ang file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    
    @staticmethod
    def parse_phase(lines) -> Phase:
        ...
    


class OxfordBinaryLoader(EBSDDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """Read Oxford Instruments .cpr/.crc file pair.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    
    def load_oxford_cpr(self, file_name: pathlib.Path) -> None:
        """
        Read an Oxford Instruments .cpr file, which is a metadata file
        describing EBSD data.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    
    def load_oxford_crc(self, file_name: pathlib.Path) -> None:
        """Read binary EBSD data from an Oxford Instruments .crc file

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    


class PythonDictLoader(EBSDDataLoader):
    def load(self, data_dict: Dict[str, Any]) -> None:
        """Construct EBSD data from a python dictionary.

        Parameters
        ----------
        data_dict
            Dictionary with keys:
                'step_size'
                'phases'
                'phase'
                'euler_angle'
                'band_contrast'

        """
        ...
    


class DICDataLoader(ABC):
    """Class containing methods for loading and checking HRDIC data

    """
    def __init__(self, file_type: str = ...) -> None:
        ...
    
    @staticmethod
    def get_loader(data_type: str) -> Type[DICDataLoader]:
        ...
    
    def checkMetadata(self) -> None:
        ...
    
    def check_data(self) -> None:
        """ Calculate size of map from loaded data and check it matches
        values from metadata.

        """
        ...
    
    @abstractmethod
    def load(self, file_name: pathlib.Path) -> None:
        ...
    


class DavisLoader(DICDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Load from Davis .txt file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    
    @staticmethod
    def load_davis_image_data(file_name: pathlib.Path) -> np.ndarray:
        """ A .txt file from DaVis containing a 2D image

        Parameters
        ----------
        file_name
            Path to file

        Returns
        -------
        np.ndarray
            Array of data.

        """
        ...
    


class OpenPivTextLoader(DICDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Load from Open PIV .txt file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    


class OpenPivBinaryLoader(DICDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Load from Open PIV .npz file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    


class PyValeLoader(DICDataLoader):
    def load(self, file_name: pathlib.Path) -> None:
        """ Load from PyVale csv or binary file.

        Parameters
        ----------
        file_name
            Path to file

        """
        ...
    


def read_until_string(file: TextIO, term_string: str, comment_char: str = ..., line_process: Optional[Callable[[str], Any]] = ..., exact: bool = ...) -> List[Any]:
    """Read lines in a file until a line starting with the `termString`
    is encountered. The file position is returned before the line starting
    with the `termString` when found. Comment and empty lines are ignored.

    Parameters
    ----------
    file
        An open python text file object.
    term_string
        String to terminate reading.
    comment_char
        Character at start of a comment line to ignore.
    line_process
        Function to apply to each line when loaded.
    exact
        A line must exactly match `termString` to stop.

    Returns
    -------
    list
        List of processed lines loaded from file.

    """
    ...

