"""
This type stub file was generated by pyright.
"""

from typing import Type

class EBSDDataWriter:
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def get_writer(datatype: str) -> Type[EBSDDataLoader]:
        ...
    


class OxfordTextWriter(EBSDDataWriter):
    def write(self, file_name: str, file_dir: str = ...) -> None:
        """ Write an Oxford Instruments .ctf file, which is a HKL single
        orientation file.

        Parameters
        ----------
        file_name
            File name.
        file_dir
            Path to file.

        """
        ...
    


