"""
This type stub file was generated by pyright.
"""

class Plot:
    """ Class used for creating and manipulating plots.

    """
    def __init__(self, ax=..., ax_params=..., fig=..., make_interactive=..., title=..., **kwargs) -> None:
        ...
    
    def set_empty_state(self): # -> None:
        ...
    
    def check_interactive(self): # -> None:
        """Checks if current plot is interactive.

        Raises
        -------
        Exception
            If plot is not interactive

        """
        ...
    
    def add_event_handler(self, eventName, eventHandler): # -> None:
        ...
    
    def add_axes(self, loc, proj=...): # -> Axes | Axes3D | None:
        """Add axis to current plot

        Parameters
        ----------
        loc
            Location of axis.
        proj : str, {2d, 3d}
            2D or 3D projection.

        Returns
        -------
        matplotlib.Axes.axes

        """
        ...
    
    def add_button(self, label, click_handler, loc=..., **kwargs): # -> None:
        """Add a button to the plot.

        Parameters
        ----------
        label : str
            Label for the button.
        click_handler
            Click handler to assign.
        loc : list(float), len 4
            Left, bottom, width, height.
        kwargs
            All other arguments passed to :class:`matplotlib.widgets.Button`.

        """
        ...
    
    def add_text_box(self, label, submit_handler=..., change_handler=..., loc=..., **kwargs): # -> TextBox:
        """Add a text box to the plot.

        Parameters
        ----------
        label : str
            Label for the button.
        submit_handler
            Submit handler to assign.
        change_handler
            Change handler to assign.
        loc : list(float), len 4
            Left, bottom, width, height.
        kwargs
            All other arguments passed to :class:`matplotlib.widgets.TextBox`.

        Returns
        -------
        matplotlotlib.widgets.TextBox

        """
        ...
    
    def add_text(self, ax, x, y, txt, **kwargs): # -> None:
        """Add text to the plot.

        Parameters
        ----------
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on.
        x : float
            x position.
        y : float
            y position.
        txt : str
            Text to write onto the plot.

        kwargs :
            All other arguments passed to :func:`matplotlib.pyplot.text`.

        """
        ...
    
    def add_arrow(self, start_end, persistent=..., clear_previous=..., label=...): # -> None:
        """Add arrow to grain plot.

        Parameters
        ----------
        start_end: 4-tuple
            Starting (x, y), Ending (x, y).
        persistent :
            If persistent, do not clear arrow with clearPrev.
        clear_previous :
            Clear all non-persistent arrows.
        label
            Label to place near arrow.

        """
        ...
    
    def set_size(self, size): # -> None:
        """Set size of plot.

        Parameters
        ----------
        size : float, float
            Width and height in inches.

        """
        ...
    
    def set_title(self, txt): # -> None:
        """Set title of plot.

        Parameters
        ----------
        txt : str
            Title to set.

        """
        ...
    
    def line_slice(self, event, plot, action=...): # -> None:
        """ Catch click and drag then draw an arrow.

        Parameters
        ----------
        event :
            Click event.
        plot : defdap.plotting.Plot
            Plot to capture clicks from.
        action
            Further action to perform.

        Examples
        ----------
        To use, add a click and release event handler to your plot, pointing to this function:

        >>> plot.add_event_handler('button_press_event',lambda e, p: line_slice(e, p))
        >>> plot.add_event_handler('button_release_event', lambda e, p: line_slice(e, p))

        """
        ...
    
    @property
    def exists(self): # -> bool:
        ...
    
    def clear(self): # -> None:
        """Clear plot.

        """
        ...
    
    def draw(self): # -> None:
        """Draw plot

        """
        ...
    


class MapPlot(Plot):
    """ Class for creating a map plot.

    """
    def __init__(self, calling_map, fig=..., ax=..., ax_params=..., make_interactive=..., **kwargs) -> None:
        """Initialise a map plot.

        Parameters
        ----------
        calling_map : Map
            DIC or EBSD map which called this plot.
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on
        ax_params :
            Passed to defdap.plotting.Plot as ax_params.
        make_interactive : bool, optional
            If true, make interactive
        kwargs
            Other arguments passed to :class:`defdap.plotting.Plot`.

        """
        ...
    
    def set_empty_state(self): # -> None:
        ...
    
    def add_map(self, map_data, vmin=..., vmax=..., cmap=..., **kwargs): # -> AxesImage:
        """Add a map to a plot.

        Parameters
        ----------
        map_data : numpy.ndarray
            Map data to plot.
        vmin : float
            Minimum value for the colour scale.
        vmax : float
            Maximum value for the colour scale.
        cmap
            Colour map.
        kwargs
            Other arguments are passed to :func:`matplotlib.pyplot.imshow`.

        Returns
        -------
        matplotlib.image.AxesImage

        """
        ...
    
    def add_colour_bar(self, label, layer=..., **kwargs): # -> None:
        """Add a colour bar to plot.

        Parameters
        ----------
        label : str
            Label for the colour bar.
        layer : int
            Layer ID.
        kwargs
            Other arguments are passed to :func:`matplotlib.pyplot.colorbar`.

        """
        ...
    
    def add_scale_bar(self, scale=...): # -> None:
        """Add scale bar to plot.

        Parameters
        ----------
        scale : float
            Size of a pixel in microns.

        """
        ...
    
    def add_grain_boundaries(self, kind=..., boundaries=..., colour=..., dilate=..., draw=..., **kwargs): # -> Collection | AxesImage:
        """Add grain boundaries to the plot.

        Parameters
        ----------
        kind : str, {"pixel", "line"}
            Type of boundaries to plot, either a boundary image or a
            collection of line segments.
        boundaries : various, optional
            Boundaries to plot, either a boundary image or a list of pairs
            of coordinates representing the start and end of each boundary 
            segment. If not provided the boundaries are loaded from the 
            calling map.

        boundaries : various, defdap.ebsd.BoundarySet
            Boundaries to plot. If not provided the boundaries are loaded from
            the calling map.

        colour : various
            One of:
              - Colour of all boundaries as a string (only option pixel kind)
              - Colour of all boundaries as RGBA tuple
              - List of values to represent colour of each line relative to a
                `norm` and `cmap`
        dilate : bool
            If true, dilate the grain boundaries.
        kwargs
            If line kind then other arguments are passed to 
            :func:`matplotlib.collections.LineCollection`.

        Returns
        -------
        Various :
            matplotlib.image.AxesImage if type is pixel

        """
        ...
    
    def add_grain_highlights(self, grain_ids, grain_colours=..., alpha=..., new_layer=...): # -> AxesImage:
        """Highlight grains in the plot.

        Parameters
        ----------
        grain_ids : list
            List of grain IDs to highlight.
        grain_colours :
            Colour to use for grain highlight.
        alpha : float
            Alpha (transparency) to use for grain highlight.
        new_layer : bool
            If true, make a new layer in img_layers.

        Returns
        -------
        matplotlib.image.AxesImage

        """
        ...
    
    def add_grain_numbers(self, fontsize=..., **kwargs): # -> None:
        """Add grain numbers to a map.

        Parameters
        ----------
        fontsize : float
            Font size.
        kwargs
            Pass other arguments to :func:`matplotlib.pyplot.text`.

        """
        ...
    
    def add_legend(self, values, labels, layer=..., **kwargs): # -> None:
        """Add a legend to a map.

        Parameters
        ----------
        values : list
            Values to find colour patched for.
        labels : list
            Labels to assign to values.
        layer : int
            Image layer to generate legend for.
        kwargs
            Pass other arguments to :func:`matplotlib.pyplot.legend`.

        """
        ...
    
    def add_points(self, x, y, update_layer=..., **kwargs): # -> PathCollection:
        """Add points to plot.

        Parameters
        ----------
        x : list of float
            x coordinates
        y : list of float
            y coordinates
        update_layer : int, optional
            Layer to place points on
        kwargs
            Other arguments passed to :func:`matplotlib.pyplot.scatter`.

        """
        ...
    
    @classmethod
    def create(cls, calling_map, map_data, fig=..., fig_params=..., ax=..., ax_params=..., plot=..., make_interactive=..., plot_colour_bar=..., vmin=..., vmax=..., cmap=..., clabel=..., plot_gbs=..., dilate_boundaries=..., boundary_colour=..., plot_scale_bar=..., scale=..., highlight_grains=..., highlight_colours=..., highlight_alpha=..., **kwargs): # -> Self:
        """Create a plot for a map.

        Parameters
        ----------
        calling_map : base.Map
            DIC or EBSD map which called this plot.
        map_data : numpy.ndarray
            Data to be plotted.
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on.
        fig_params :
            Passed to defdap.plotting.Plot.
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on.
        ax_params :
            Passed to defdap.plotting.Plot as ax_params.
        plot : defdap.plotting.Plot
            If none, use current plot.
        make_interactive :
            If true, make plot interactive
        plot_colour_bar : bool
            If true, plot a colour bar next to the map.
        vmin : float, optional
            Minimum value for the colour scale.
        vmax : float, optional
            Maximum value for the colour scale.
        cmap : str
            Colour map.
        clabel : str
            Label for the colour bar.
        plot_gbs : bool
            If true, plot the grain boundaries on the map.
        dilate_boundaries : bool
            If true, dilate the grain boundaries.
        boundary_colour : str
            Colour to use for the grain boundaries.
        plot_scale_bar : bool
            If true, plot a scale bar in the map.
        scale : float
            Size of pixel in microns.
        highlight_grains : list(int)
            List of grain IDs to highlight.
        highlight_colours : str
            Colour to highlight grains.
        highlight_alpha : float
            Alpha (transparency) by which to highlight grains.
        kwargs :
            All other arguments passed to :func:`defdap.plotting.MapPlot.add_map`

        Returns
        -------
        defdap.plotting.MapPlot

        """
        ...
    


class GrainPlot(Plot):
    """ Class for creating a map for a grain.

    """
    def __init__(self, calling_grain, fig=..., ax=..., ax_params=..., make_interactive=..., **kwargs) -> None:
        ...
    
    def set_empty_state(self): # -> None:
        ...
    
    def addMap(self, map_data, vmin=..., vmax=..., cmap=..., **kwargs): # -> AxesImage:
        """Add a map to a grain plot.

        Parameters
        ----------
        map_data : numpy.ndarray
            Grain data to plot
        vmin : float
            Minimum value for the colour scale.
        vmax : float
            Maximum value for the colour scale.
        cmap
            Colour map to use.
        kwargs
            Other arguments are passed to :func:`matplotlib.pyplot.imshow`.

        Returns
        -------
        matplotlib.image.AxesImage

        """
        ...
    
    def add_colour_bar(self, label, layer=..., **kwargs): # -> None:
        """Add colour bar to grain plot.

        Parameters
        ----------
        label : str
            Label to add to colour bar.
        layer : int
            Layer on which to add colourbar.
        kwargs
            Other arguments passed to :func:`matplotlib.pyplot.colorbar`.

        """
        ...
    
    def add_scale_bar(self, scale=...): # -> None:
        """Add scale bar to grain plot.

        Parameters
        ----------
        scale : float
            Size of pixel in micron.

        """
        ...
    
    def add_traces(self, angles, colours, top_only=..., pos=..., **kwargs): # -> None:
        """Add slip trace angles to grain plot. Illustrated by lines
        crossing through central pivot point to create a circle.

        Parameters
        ----------
        angles : list
            Angles of slip traces.
        colours : list
            Colours to plot.
        top_only : bool, optional
            If true, plot only a semicircle instead of a circle.
        pos : tuple
            Position of slip traces.
        kwargs
            Other arguments are passed to :func:`matplotlib.pyplot.quiver`

        """
        ...
    
    def add_slip_traces(self, colours=..., **kwargs): # -> None:
        """Add slip traces to plot, based on the calling grain's slip systems.

        Parameters
        ----------
        colours : list
            Colours of each trace.
        top_only : bool, optional
            If true, plot only a semicircle instead of a circle.
        kwargs
            Other arguments are passed to :func:`defdap.plotting.GrainPlot.add_traces`

        """
        ...
    
    def add_slip_bands(self, grain_map_data, colour=..., thres=..., min_dist=..., **kwargs): # -> None:
        """Add lines representing slip bands detected by Radon transform
        in :func:`~defdap.hrdic.grain.calc_slip_bands`.

        Parameters
        ----------
        grain_map_data :
            Map data to pass to :func:`~defdap.hrdic.Grain.calc_slip_bands`.
        colour : str
            Colour of traces.
        thres : float
            Threshold to use in :func:`~defdap.hrdic.Grain.calc_slip_bands`.
        min_dist :
            Minimum angle between bands in :func:`~defdap.hrdic.Grain.calc_slip_bands`.
        kwargs
            Other arguments are passed to :func:`defdap.plotting.GrainPlot.add_traces`.

        """
        ...
    
    @classmethod
    def create(cls, calling_grain, map_data, fig=..., fig_params=..., ax=..., ax_params=..., plot=..., make_interactive=..., plot_colour_bar=..., vmin=..., vmax=..., cmap=..., clabel=..., plot_scale_bar=..., scale=..., plot_slip_traces=..., plot_slip_bands=..., **kwargs): # -> Self:
        """Create grain plot.

        Parameters
        ----------
        calling_grain : base.Grain
            DIC or EBSD grain which called this plot.
        map_data :
            Data to be plotted.
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on.
        fig_params :
            Passed to defdap.plotting.Plot.
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on.
        ax_params :
            Passed to defdap.plotting.Plot as ax_params.
        plot : defdap.plotting.Plot
            If none, use current plot.
        make_interactive :
            If true, make plot interactive
        plot_colour_bar : bool
            If true, plot a colour bar next to the map.
        vmin : float
            Minimum value for the colour scale.
        vmax : float
            Maximum value for the colour scale.
        cmap :
            Colour map.
        clabel : str
            Label for the colour bar.
        plot_scale_bar : bool
            If true, plot a scale bar in the map.
        scale : float
            Size of pizel in microns.
        plot_slip_traces : bool
            If true, plot slip traces with :func:`~defdap.plotting.GrainPlot.add_slip_traces`
        plot_slip_bands : bool
            If true, plot slip traces with :func:`~defdap.plotting.GrainPlot.add_slip_bands`
        kwargs :
            All other arguments passed to :func:`defdap.plotting.GrainPlot.add_map`

        Returns
        -------
        defdap.plotting.GrainPlot

        """
        ...
    


class PolePlot(Plot):
    """ Class for creating an inverse pole figure plot.

    """
    def __init__(self, plot_type, crystal_sym, projection=..., fig=..., ax=..., ax_params=..., make_interactive=..., **kwargs) -> None:
        ...
    
    def add_axis(self): # -> None:
        """Draw axes on the IPF based on crystal symmetry.

        Raises
        -------
        NotImplementedError
            If a crystal type other than 'cubic' or 'hexagonal' are selected.

        """
        ...
    
    def add_line(self, start_point, end_point, plot_syms=..., res=..., **kwargs): # -> None:
        """Draw lines on the IPF plot.

        Parameters
        ----------
        start_point : tuple
            Start point in crystal coordinates (i.e. [0,0,1]).
        end_point : tuple
            End point in crystal coordinates, (i.e. [1,0,0]).
        plot_syms : bool, optional
            If true, plot all symmetrically equivelant points.
        res : int
            Number of points within each line to plot.
        kwargs
            All other arguments are passed to :func:`matplotlib.pyplot.plot`.

        """
        ...
    
    def label_point(self, point, label=..., plot_syms=..., pad_x=..., pad_y=..., **kwargs): # -> None:
        """Place a label near a coordinate in the pole plot.

        Parameters
        ----------
        point : tuple
            (x, y) coordinate to place text.
        label : str, optional
            Text to use in label.
        pad_x : int, optional
            Pad added to x coordinate.
        pad_y : int, optional
            Pad added to y coordinate.
        kwargs
            Other arguments are passed to :func:`matplotlib.axes.Axes.text`.

        """
        ...
    
    def add_points(self, alpha_ang, beta_ang, marker_colour=..., marker_size=..., **kwargs): # -> None:
        """Add a point to the pole plot.

        Parameters
        ----------
        alpha_ang
            Inclination angle to plot.
        beta_ang
            Azimuthal angle (around z axis from x in anticlockwise as per ISO) to plot.
        marker_colour : str or list(str), optional
            Colour of marker. If two specified, then the point will have two
            semicircles of different colour.
        marker_size : float
            Size of marker.
        kwargs
            Other arguments are passed to :func:`matplotlib.axes.Axes.scatter`.

        Raises
        -------
        Exception
            If more than two colours are specified

        """
        ...
    
    def add_colour_bar(self, label, layer=..., **kwargs): # -> None:
        """Add a colour bar to the pole plot.

        Parameters
        ----------
        label : str
            Label to place next to colour bar.
        layer : int
            Layer number to add the colour bar to.
        kwargs
            Other argument are passed to :func:`matplotlib.pyplot.colorbar`.

        """
        ...
    
    def add_legend(self, label=..., number=..., layer=..., scaling=..., **kwargs): # -> None:
        """Add a marker size legend to the pole plot.

        Parameters
        ----------
        label : str
            Label to place next to legend.
        number :
            Number of markers to plot in legend.
        layer : int
            Layer number to add the colour bar to.
        scaling : float
            Scaling applied to the data.
        kwargs
            Other argument are passed to :func:`matplotlib.pyplot.legend`.

        """
        ...
    
    @staticmethod
    def stereo_project(*args): # -> tuple[NDArray[Any], NDArray[Any]]:
        """Stereographic projection of pole direction or pair of polar angles.

        Parameters
        ----------
        args : numpy.ndarray, len 2 or 3
            2 arguments for polar angles or 3 arguments for pole directions.

        Returns
        -------
        float, float
            x coordinate, y coordinate

        Raises
        -------
        Exception
            If input array has incorrect length

        """
        ...
    
    @staticmethod
    def lambert_project(*args): # -> tuple[NDArray[Any], NDArray[Any]]:
        """Lambert Projection of pole direction or pair of polar angles.

        Parameters
        ----------
        args : numpy.ndarray, len 2 or 3
            2 arguments for polar angles or 3 arguments for pole directions.

        Returns
        -------
        float, float
            x coordinate, y coordinate

        Raises
        -------
        Exception
            If input array has incorrect length

        """
        ...
    


class HistPlot(Plot):
    """ Class for creating a histogram.

    """
    def __init__(self, plot_type=..., axes_type=..., density=..., fig=..., ax=..., ax_params=..., make_interactive=..., **kwargs) -> None:
        """Initialise a histogram plot

        Parameters
        ----------
        plot_type: str, {'scatter', 'bar', 'step'}
            Type of plot to use
        axes_type : str, {'linear', 'logx', 'logy', 'loglog', 'None'}, optional
            If 'log' is specified, logarithmic scale is used.
        density :
            If true, histogram is normalised such that the integral sums to 1.
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on.
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on.
        ax_params :
            Passed to defdap.plotting.Plot as ax_params.
        make_interactive : bool
            If true, make the plot interactive.
        kwargs
            Other arguments are passed to :class:`defdap.plotting.Plot`

        """
        ...
    
    def add_hist(self, hist_data, bins=..., range=..., line=..., label=..., **kwargs): # -> None:
        """Add a histogram to the current plot

        Parameters
        ----------
        hist_data : numpy.ndarray
            Data to be used in the histogram.
        bins : int
            Number of bins to use for histogram.
        range : tuple or None, optional
            The lower and upper range of the bins
        line : str, optional
            Marker or line type to be used.
        label : str, optional
            Label to use for data (used for legend).
        kwargs
            Other arguments are passed to :func:`numpy.histogram`

        """
        ...
    
    def add_legend(self, **kwargs): # -> None:
        """Add legend to histogram.

        Parameters
        ----------
        kwargs
            All arguments passed to :func:`matplotlib.axes.Axes.legend`.

        """
        ...
    
    @classmethod
    def create(cls, hist_data, fig=..., fig_params=..., ax=..., ax_params=..., plot=..., make_interactive=..., plot_type=..., axes_type=..., density=..., bins=..., range=..., line=..., label=..., **kwargs): # -> Self:
        """Create a histogram plot.

        Parameters
        ----------
        hist_data : numpy.ndarray
            Data to be used in the histogram.
        fig : matplotlib.figure.Figure
            Matplotlib figure to plot on.
        fig_params :
            Passed to defdap.plotting.Plot.
        ax : matplotlib.axes.Axes
            Matplotlib axis to plot on.
        ax_params :
            Passed to defdap.plotting.Plot as ax_params.
        plot : defdap.plotting.HistPlot
            Plot where histgram is created. If none, a new plot is created.
        make_interactive : bool, optional
            If true, make plot interactive.
        plot_type: str, {'scatter', 'bar', 'barfilled', 'step'}
            Type of plot to use
        axes_type : str, {'linear', 'logx', 'logy', 'loglog', 'None'}, optional
            If 'log' is specified, logarithmic scale is used.
        density :
            If true, histogram is normalised such that the integral sums to 1.
        bins : int
            Number of bins to use for histogram.
        range : tuple or None, optional
            The lower and upper range of the bins
        line : str, optional
            Marker or line type to be used.
        label : str, optional
            Label to use for data (is used for legend).
        kwargs
            Other arguments are passed to :func:`defdap.plotting.HistPlot.add_hist`

        Returns
        -------
        defdap.plotting.HistPlot

        """
        ...
    


class CrystalPlot(Plot):
    """ Class for creating a 3D plot for plotting unit cells.

    """
    def __init__(self, fig=..., ax=..., ax_params=..., make_interactive=..., **kwargs) -> None:
        """Initialise a 3D plot.

        Parameters
        ----------
        fig : matplotlib.pyplot.Figure
            Figure to plot to.
        ax : matplotlib.pyplot.Axis
            Axis to plot to.
        ax_params
            Passed to defdap.plotting.Plot as ax_params.
        make_interactive : bool, optional
            If true, make plot interactive.
        kwargs
            Other arguments are passed to :class:`defdap.plotting.Plot`.

        """
        ...
    
    def add_verts(self, verts, **kwargs): # -> None:
        """Plots planes, defined by the vertices provided.

        Parameters
        ----------
        verts : list
            List of vertices.
        kwargs
            Other arguments are passed to :class:`matplotlib.collections.PolyCollection`.

        """
        ...
    


