"""
This type stub file was generated by pyright.
"""

import numpy as np
from defdap import plotting
from typing import List, Optional, Tuple, Union

class Quat:
    """Class used to define and perform operations on quaternions. These
    are interpreted in the passive sense.

    """
    __slots__ = ...
    def __init__(self, *args, allow_southern: Optional[bool] = ...) -> None:
        """
        Construct a Quat object from 4 quat coefficients or an array of
        quat coefficients.

        Parameters
        ----------
        *args
            Variable length argument list.
        allow_southern
            if False, move quat to northern hemisphere.

        """
        ...
    
    @classmethod
    def from_euler_angles(cls, ph1: float, phi: float, ph2: float) -> Quat:
        """Create a quat object from 3 Bunge euler angles.

        Parameters
        ----------
        ph1
            First Euler angle, rotation around Z in radians.
        phi
            Second Euler angle, rotation around new X in radians.
        ph2
            Third Euler angle, rotation around new Z in radians.

        Returns
        -------
        defdap.quat.Quat
            Initialised Quat object.

        """
        ...
    
    @classmethod
    def from_axis_angle(cls, axis: np.ndarray, angle: float) -> Quat:
        """Create a quat object from a rotation around an axis. This
        creates a quaternion to represent the passive rotation (-ve axis).

        Parameters
        ----------
        axis
            Axis that the rotation is applied around.
        angle
            Magnitude of rotation in radians.

        Returns
        -------
        defdap.quat.Quat
            Initialised Quat object.

        """
        ...
    
    def euler_angles(self) -> np.ndarray:
        """Calculate the Euler angle representation for this rotation.

        Returns
        -------
        eulers : numpy.ndarray, shape 3
            Bunge euler angles (in radians).

        References
        ----------
            Melcher A. et al., 'Conversion of EBSD data by a quaternion
            based algorithm to be used for grain structure simulations',
            Technische Mechanik, 30(4)401 – 413

            Rowenhorst D. et al., 'Consistent representations of and
            conversions between 3D rotations',
            Model. Simul. Mater. Sci. Eng., 23(8)

        """
        ...
    
    def rot_matrix(self) -> np.ndarray:
        """Calculate the rotation matrix representation for this rotation.

        Returns
        -------
        rot_matrix : numpy.ndarray, shape (3, 3)
            Rotation matrix.

        References
        ----------
            Melcher A. et al., 'Conversion of EBSD data by a quaternion
            based algorithm to be used for grain structure simulations',
            Technische Mechanik, 30(4)401 – 413

            Rowenhorst D. et al., 'Consistent representations of and
            conversions between 3D rotations',
            Model. Simul. Mater. Sci. Eng., 23(8)

        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, right: Quat) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __mul__(self, right: Quat, allow_southern: bool = ...) -> Quat:
        ...
    
    def dot(self, right: Quat) -> float:
        """ Calculate dot product between two quaternions.

        Parameters
        ----------
        right
            Right hand quaternion.

        Returns
        -------
        float
            Dot product.

        """
        ...
    
    def __add__(self, right: Quat) -> Quat:
        ...
    
    def __iadd__(self, right: Quat) -> Quat:
        ...
    
    def __getitem__(self, key: int) -> float:
        ...
    
    def __setitem__(self, key: int, value: float) -> None:
        ...
    
    def norm(self) -> float:
        """Calculate the norm of the quaternion.

        Returns
        -------
        float
            Norm of the quaternion.

        """
        ...
    
    def normalise(self) -> Quat:
        """ Normalise the quaternion (turn it into an unit quaternion).

        Returns
        -------
        defdap.quat.Quat
            Normalised quaternion.

        """
        ...
    
    @property
    def conjugate(self) -> Quat:
        """Calculate the conjugate of the quaternion.

        Returns
        -------
        defdap.quat.Quat
            Conjugate of quaternion.

        """
        ...
    
    def transform_vector(self, vector: Union[Tuple, List, np.ndarray]) -> np.ndarray:
        """
        Transforms vector by the quaternion. For passive EBSD quaterions
        this is a transformation from sample space to crystal space.
        Perform on conjugate of quaternion for crystal to sample. For a
        quaternion representing a passive rotation from CS1 to CS2 and a
        fixed vector V defined in CS1, this gives the coordinates
        of V in CS2.

        Parameters
        ----------
        vector : numpy.ndarray, shape 3 or equivalent
            Vector to transform.

        Returns
        -------
        numpy.ndarray, shape 3
            Transformed vector.

        """
        ...
    
    def mis_ori(self, right: Quat, sym_group: str, return_quat: Optional[int] = ...) -> Tuple[float, Quat]:
        """
        Calculate misorientation angle between 2 orientations taking
        into account the symmetries of the crystal structure.
        Angle is 2*arccos(output).

        Parameters
        ----------
        right
            Orientation to find misorientation to.
        sym_group
            Crystal type (cubic, hexagonal).
        return_quat
            What to return: 0 for minimum misorientation, 1 for
            symmetric equivalent with minimum misorientation, 2 for both.

        Returns
        -------
        float
            Minimum misorientation.
        defdap.quat.Quat
            Symmetric equivalent orientation with minimum misorientation.

        """
        ...
    
    def mis_ori_axis(self, right: Quat) -> np.ndarray:
        """
        Calculate misorientation axis between 2 orientations. This
        does not consider symmetries of the crystal structure.

        Parameters
        ----------
        right : defdap.quat.Quat
            Orientation to find misorientation axis to.

        Returns
        -------
        numpy.ndarray, shape 3
            Axis of misorientation.

        """
        ...
    
    def plot_ipf(self, direction: np.ndarray, sym_group: str, projection: Optional[str] = ..., plot: Optional[plotting.Plot] = ..., fig: Optional[matplotlib.figure.Figure] = ..., ax: Optional[matplotlib.axes.Axes] = ..., plot_colour_bar: Optional[bool] = ..., clabel: Optional[str] = ..., make_interactive: Optional[bool] = ..., marker_colour: Optional[Union[List[str], str]] = ..., marker_size: Optional[float] = ..., **kwargs) -> plotting.PolePlot:
        """
        Plot IPF of orientation, with relation to specified sample direction.

        Parameters
        ----------
        direction
            Sample reference direction for IPF.
        sym_group
            Crystal type (cubic, hexagonal).
        projection
             Projection to use. Either string (stereographic or lambert)
             or a function.
        plot
            Defdap plot to plot on.
        fig
            Figure to plot on, if not provided the current
            active axis is used.
        ax
            Axis to plot on, if not provided the current
            active axis is used.
        make_interactive
            If true, make the plot interactive.
        plot_colour_bar : bool
            If true, plot a colour bar next to the map.
        clabel : str
            Label for the colour bar.
        marker_colour: str or list of str
            Colour of markers (only used for half and half colouring,
            otherwise use argument c).
        marker_size
            Size of markers (only used for half and half colouring,
            otherwise use argument s).
        kwargs
            All other arguments are passed to :func:`defdap.plotting.PolePlot.add_points`.

        """
        ...
    
    def plot_unit_cell(self, crystal_structure: defdap.crystal.CrystalStructure, OI: Optional[bool] = ..., plot: Optional[plotting.CrystalPlot] = ..., fig: Optional[matplotlib.figure.Figure] = ..., ax: Optional[matplotlib.axes.Axes] = ..., make_interactive: Optional[bool] = ..., **kwargs) -> plotting.CrystalPlot:
        """Plots a unit cell.

        Parameters
        ----------
        crystal_structure
            Crystal structure.
        OI
            True if using oxford instruments system.
        plot
            Plot object to plot to.
        fig
            Figure to plot on, if not provided the current active axis is used.
        ax
            Axis to plot on, if not provided the current active axis is used.
        make_interactive
            True to make the plot interactive.
        kwargs
            All other arguments are passed to :func:`defdap.plotting.CrystalPlot.add_verts`.

        """
        ...
    
    @staticmethod
    def create_many_quats(eulerArray: np.ndarray) -> np.ndarray:
        """Create a an array of quats from an array of Euler angles.

        Parameters
        ----------
        eulerArray
            Array of Bunge Euler angles of shape 3 x n x ... x m.

        Returns
        -------
        quats : numpy.ndarray(defdap.quat.Quat)
            Array of quat objects of shape n x ... x m.

        """
        ...
    
    @staticmethod
    def multiply_many_quats(quats: List[Quat], right: Quat) -> List[Quat]:
        """ Multiply all quats in a list of quats, by a single quat.

        Parameters
        ----------
        quats
            List of quats to be operated on.
        right
            Single quaternion to multiply with the list of quats.

        Returns
        -------
        list(defdap.quat.Quat)

        """
        ...
    
    @staticmethod
    def extract_quat_comps(quats: np.ndarray) -> np.ndarray:
        """Return a NumPy array of the provided quaternion components

        Input quaternions may be given as a list of Quat objects or any iterable
        whose items have 4 components which map to the quaternion.

        Parameters
        ----------
        quats : numpy.ndarray(defdap.quat.Quat)
            A list of Quat objects to return the components of

        Returns
        -------
        numpy.ndarray
            Array of quaternion components, shape (4, ..)

        """
        ...
    
    @staticmethod
    def calc_sym_eqvs(quats: np.ndarray, sym_group: str, dtype: Optional[type] = ...) -> np.ndarray:
        """Calculate all symmetrically equivalent quaternions of given quaternions.

        Parameters
        ----------
        quats : numpy.ndarray(defdap.quat.Quat)
            Array of quat objects.
        sym_group
            Crystal type (cubic, hexagonal).
        dtype
            Datatype used for calculation, defaults to `float`.

        Returns
        -------
        quat_comps: numpy.ndarray, shape: (numSym x 4 x numQuats)
            Array containing all symmetrically equivalent quaternion components of input quaternions.

        """
        ...
    
    @staticmethod
    def calc_average_ori(quat_comps: np.ndarray) -> Quat:
        """Calculate the average orientation of given quats.

        Parameters
        ----------
        quat_comps : numpy.ndarray
            Array containing all symmetrically equivalent quaternion components of given quaternions
            (shape: numSym x 4 x numQuats), can be calculated with :func:`Quat.calc_sym_eqvs`.

        Returns
        -------
        av_ori : defdap.quat.Quat
            Average orientation of input quaternions.

        """
        ...
    
    @staticmethod
    def calcMisOri(quat_comps: np.ndarray, ref_ori: Quat) -> Tuple[np.ndarray, Quat]:
        """Calculate the misorientation between the quaternions and a reference quaternion.

        Parameters
        ----------
        quat_comps
            Array containing all symmetrically equivalent quaternion components of given quaternions
            (shape: numSym x 4 x numQuats), can be calculated from quats with :func:`Quat.calc_sym_eqvs` .
        ref_ori
            Reference orientation.

        Returns
        -------
        min_mis_oris : numpy.ndarray, len numQuats
            Minimum misorientation between quats and reference orientation.
        min_quat_comps : defdap.quat.Quat
            Quaternion components describing minimum misorientation between quats and reference orientation.

        """
        ...
    
    @staticmethod
    def polar_angles(x: np.ndarray, y: np.ndarray, z: np.ndarray): # -> tuple[NDArray[Any], NDArray[Any]]:
        """Convert Cartesian coordinates to polar coordinates, for an
        unit vector.

        Parameters
        ----------
        x : numpy.ndarray(float)
            x coordinate.
        y : numpy.ndarray(float)
            y coordinate.
        z : numpy.ndarray(float)
            z coordinate.

        Returns
        -------
        float, float
            inclination angle and azimuthal angle (around z axis from x
            in anticlockwise as per ISO).

        """
        ...
    
    @staticmethod
    def calc_ipf_colours(quats: np.ndarray, direction: np.ndarray, sym_group: str, dtype: Optional[type] = ...) -> np.ndarray:
        """
        Calculate the RGB colours, based on the location of the given quats
        on the fundamental region of the IPF for the sample direction specified.

        Parameters
        ----------
        quats : numpy.ndarray(defdap.quat.Quat)
            Array of quat objects.
        direction
            Direction in sample space.
        sym_group
            Crystal type (cubic, hexagonal).
        dtype
            Data type to use for calculation.

        Returns
        -------
        numpy.ndarray, shape (3, num_quats)
            Array of rgb colours for each quat.

        References
        -------
        Stephen Cluff (BYU) - IPF_rgbcalc.m subroutine in OpenXY
        https://github.com/BYU-MicrostructureOfMaterials/OpenXY/blob/master/Code/PlotIPF.m

        """
        ...
    
    @staticmethod
    def calc_fund_dirs(quats: np.ndarray, direction: np.ndarray, sym_group: str, dtype: Optional[type] = ..., triangle: Optional[str] = ...) -> Tuple[np.ndarray, np.ndarray]:
        """
        Transform the sample direction to crystal coords based on the quats
        and find the ones in the fundamental sector of the IPF.

        Parameters
        ----------
        quats: array_like(defdap.quat.Quat)
            Array of quat objects.
        direction
            Direction in sample space.
        sym_group
            Crystal type (cubic, hexagonal).
        dtype
            Data type to use for calculation.
        triangle:  str, optional
            Triangle convention to use for hexagonal symmetry (up, down). If None,
            defaults to the value in `defaults['ipf_triangle_convention']`.

        Returns
        -------
        float, float
            inclination angle and azimuthal angle (around z axis from x in anticlockwise).

        """
        ...
    
    @staticmethod
    def sym_eqv(symGroup: str) -> List[Quat]:
        """Returns all symmetric equivalents for a given crystal type.
        LEGACY: move to use symmetries defined in crystal structures

        Parameters
        ----------
        symGroup : str
            Crystal type (cubic, hexagonal).

        Returns
        -------
        list of defdap.quat.Quat
            Symmetrically equivalent quats.

        """
        ...
    


