"""
This type stub file was generated by pyright.
"""

def report_progress(message: str = ...): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]]:
    """Decorator for reporting progress of given function

    Parameters
    ----------
    message
        Message to display (prefixed by 'Starting ', progress percentage
        and then 'Finished '

    References
    ----------
    Inspiration from :
    https://gist.github.com/Garfounkel/20aa1f06234e1eedd419efe93137c004

    """
    ...

class Datastore:
    """Storage of data and metadata, with methods to allow derived data
    to be calculated only when accessed.

    Attributes
    ----------
    _store : dict of dict
        Storage for data and metadata, keyed by data name. Each item is
        a dict with at least a `data` key, all other items are metadata,
        possibly including:
            type : str
                Type of data stored:
                    `map` - at least a 2-axis array, trailing axes are spatial
            order : int
                Tensor order of the data
            unit : str
                Measurement unit the data is stored in
            plot_params : dict
                Dictionary of the default parameters used to plot
    _generators: dict
        Methods to generate derived data, keyed by tuple of data names
        that the method produces.

    """
    __slots__ = ...
    _been_to = ...
    @staticmethod
    def generate_id(): # -> UUID:
        ...
    
    def __init__(self, group_id=..., crop_func=..., mask_func=...) -> None:
        ...
    
    def __len__(self): # -> int:
        """Number of data in the store, including data not yet generated."""
        ...
    
    def __str__(self) -> str:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    
    def __getitem__(self, key): # -> None:
        """Get data or metadata

        Parameters
        ----------
        key : str or tuple of str
            Either the data name or tuple of data name and metadata name.

        Returns
        -------
        data or metadata

        """
        ...
    
    def __setitem__(self, key, val): # -> None:
        """Set data or metadata of item that already exists.

        Parameters
        ----------
        key : str or tuple of str
            Either the data name or tuple of data name and metadata name.
        val : any
            Value to set

        """
        ...
    
    def __getattr__(self, key): # -> None:
        """Get data

        """
        ...
    
    def __setattr__(self, key, val): # -> None:
        """Set data of item that already exists.

        """
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        """Iterate through the data names. Allows use of `*datastore` to
        get all keys in the store, imitating functionality of a dictionary.

        """
        ...
    
    def keys(self): # -> list[Any]:
        """Get the names of all data items. Allows use of `**datastore`
        to get key-value pairs, imitating functionality of a dictionary.

        """
        ...
    
    def lookup_derivative_keys(self, derivative): # -> list[Any]:
        ...
    
    def add(self, key, data, **kwargs): # -> None:
        """Add an item to the datastore.

        Parameters
        ----------
        key : str
            Name of the data.
        data : any
            Data to store.
        kwargs : dict
            Key-value pairs stored as the items metadata.

        """
        ...
    
    def add_generator(self, keys, func, metadatas=..., **kwargs): # -> None:
        """Add a data generator method that produces one or more data.

        Parameters
        ----------
        keys: str or tuple of str
            Name(s) of data that the generator produces.
        func: callable
            Method that produces the data. Should return the same number
            of values as there are `keys`.
        metadatas : list of dict
            Metadata dicts for each of data items produced.
        kwargs : dict
            Key-value pairs stored as the items metadata for every data
            item produced.

        """
        ...
    
    def add_derivative(self, datastore, derive_func, in_props=..., out_props=..., pass_ref=...): # -> None:
        ...
    
    def generate(self, key, return_val=..., **kwargs): # -> None:
        """Generate data from the associated data generation method and
        store if metadata `save` is not set to False.

        Parameters
        ----------
        key : str
            Name of the data to generate.

        Returns
        -------
        Requested data after generating.

        """
        ...
    
    def update(self, other, priority=...): # -> None:
        """Update with data items stored in `other`.

        Parameters
        ----------
        other : defdap.utils.Datastore
        priority : str
            Which datastore to keep an item from if the same name exists
            in both. Default is to prioritise `other`.

        """
        ...
    
    def get_metadata(self, key, attr, value=...): # -> None:
        """Get metadata value with a default returned if it does not
        exist. Imitating the `get()` method of a dictionary.

        Parameters
        ----------
        key : str
            Name of the data item.
        attr : str
            Metadata to get.
        value : any
            Default value to return if metadata does not exist.

        Returns
        -------
        Metadata value or the default value.

        """
        ...
    


class DataGenerationError(Exception):
    ...


