// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go_backend/ent/chatsession"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ChatSession is the model entity for the ChatSession schema.
type ChatSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatSessionQuery when eager-loading is set.
	Edges                ChatSessionEdges `json:"edges"`
	message_chat_session *uuid.UUID
	selectValues         sql.SelectValues
}

// ChatSessionEdges holds the relations/edges for other nodes in the graph.
type ChatSessionEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e ChatSessionEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatsession.FieldCreatedAt, chatsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case chatsession.FieldID:
			values[i] = new(uuid.UUID)
		case chatsession.ForeignKeys[0]: // message_chat_session
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatSession fields.
func (_m *ChatSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatsession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chatsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chatsession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field message_chat_session", values[i])
			} else if value.Valid {
				_m.message_chat_session = new(uuid.UUID)
				*_m.message_chat_session = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatSession.
// This includes values selected through modifiers, order, etc.
func (_m *ChatSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ChatSession entity.
func (_m *ChatSession) QueryUser() *UserQuery {
	return NewChatSessionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ChatSession.
// Note that you need to call ChatSession.Unwrap() before calling this method if this ChatSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatSession) Update() *ChatSessionUpdateOne {
	return NewChatSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatSession) Unwrap() *ChatSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatSession) String() string {
	var builder strings.Builder
	builder.WriteString("ChatSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatSessions is a parsable slice of ChatSession.
type ChatSessions []*ChatSession
