// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go_backend/ent/chatsession"
	"go_backend/ent/message"
	"go_backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v message.Role) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *message.Role) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddChatSessionIDs adds the "chat_session" edge to the ChatSession entity by IDs.
func (_u *MessageUpdate) AddChatSessionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.AddChatSessionIDs(ids...)
	return _u
}

// AddChatSession adds the "chat_session" edges to the ChatSession entity.
func (_u *MessageUpdate) AddChatSession(v ...*ChatSession) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatSessionIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChatSession clears all "chat_session" edges to the ChatSession entity.
func (_u *MessageUpdate) ClearChatSession() *MessageUpdate {
	_u.mutation.ClearChatSession()
	return _u
}

// RemoveChatSessionIDs removes the "chat_session" edge to ChatSession entities by IDs.
func (_u *MessageUpdate) RemoveChatSessionIDs(ids ...uuid.UUID) *MessageUpdate {
	_u.mutation.RemoveChatSessionIDs(ids...)
	return _u
}

// RemoveChatSession removes "chat_session" edges to ChatSession entities.
func (_u *MessageUpdate) RemoveChatSession(v ...*ChatSession) *MessageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.ChatSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatSessionIDs(); len(nodes) > 0 && !_u.mutation.ChatSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v message.Role) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *message.Role) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddChatSessionIDs adds the "chat_session" edge to the ChatSession entity by IDs.
func (_u *MessageUpdateOne) AddChatSessionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.AddChatSessionIDs(ids...)
	return _u
}

// AddChatSession adds the "chat_session" edges to the ChatSession entity.
func (_u *MessageUpdateOne) AddChatSession(v ...*ChatSession) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatSessionIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChatSession clears all "chat_session" edges to the ChatSession entity.
func (_u *MessageUpdateOne) ClearChatSession() *MessageUpdateOne {
	_u.mutation.ClearChatSession()
	return _u
}

// RemoveChatSessionIDs removes the "chat_session" edge to ChatSession entities by IDs.
func (_u *MessageUpdateOne) RemoveChatSessionIDs(ids ...uuid.UUID) *MessageUpdateOne {
	_u.mutation.RemoveChatSessionIDs(ids...)
	return _u
}

// RemoveChatSession removes "chat_session" edges to ChatSession entities.
func (_u *MessageUpdateOne) RemoveChatSession(v ...*ChatSession) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatSessionIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.ChatSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatSessionIDs(); len(nodes) > 0 && !_u.mutation.ChatSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ChatSessionTable,
			Columns: []string{message.ChatSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
