// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go_backend/ent/chatsession"
	"go_backend/ent/message"
	"go_backend/ent/schema"
	"go_backend/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatsessionFields := schema.ChatSession{}.Fields()
	_ = chatsessionFields
	// chatsessionDescCreatedAt is the schema descriptor for created_at field.
	chatsessionDescCreatedAt := chatsessionFields[1].Descriptor()
	// chatsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatsession.DefaultCreatedAt = chatsessionDescCreatedAt.Default.(func() time.Time)
	// chatsessionDescUpdatedAt is the schema descriptor for updated_at field.
	chatsessionDescUpdatedAt := chatsessionFields[2].Descriptor()
	// chatsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chatsession.DefaultUpdatedAt = chatsessionDescUpdatedAt.Default.(func() time.Time)
	// chatsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chatsession.UpdateDefaultUpdatedAt = chatsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// chatsessionDescID is the schema descriptor for id field.
	chatsessionDescID := chatsessionFields[0].Descriptor()
	// chatsession.DefaultID holds the default value on creation for the id field.
	chatsession.DefaultID = chatsessionDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[1].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
